### ISSUE TITLE
Minimal example from readme not working

### ISSUE THREAD

**Issue by some-user123** [deeplay-io/nice-grpc#217]
I tried to follow the [readme](https://github.com/deeplay-io/nice-grpc/blob/master/packages/nice-grpc/README.md) and implement the most simple case I could think of:

```proto
// hello.proto
syntax = "proto3";

message HelloRequest {
    string name = 1;
}

message HelloResponse {
    string message = 1;
}

service HelloService {
    rpc SayHello (HelloRequest) returns (HelloResponse) {}
}
```

Compiled this file using `ts-proto` and created server

```js
// server-nice.ts
import {createServer} from 'nice-grpc';
import {HelloServiceDefinition} from './compiled_proto/hello';
import {
    HelloServiceServiceImplementation,
    HelloRequest,
    HelloResponse,
    DeepPartial,
  } from './compiled_proto/hello';
  
  const helloServiceImpl: HelloServiceServiceImplementation = {
    async sayHello(
      request: HelloRequest,
    ): Promise<DeepPartial<HelloResponse>> {
      const response: HelloResponse = { message: "Hello " + request.name }
      return response;
    },
  };

const server = createServer();
server.add(HelloServiceDefinition, helloServiceImpl);
await server.listen('127.0.0.1:50051');
```

and client

```js
// client-nice.ts
import {createChannel, createClient} from 'nice-grpc';
import {
  HelloServiceClient,
  HelloServiceDefinition,
} from './compiled_proto/hello';

const channel = createChannel('127.0.0.1:50051');
const client: HelloServiceClient = createClient(
  HelloServiceDefinition,
  channel,
);

const response = await client.sayHello({name: "World"})
console.log(response)

channel.close()
```

Starting the server works.
```shell
$ ts-node server-nice.ts
```

The client in a separate shell complains:
```shell
$ ts-node client-nice.ts
...
...\node_modules\.pnpm\nice-grpc@2.0.0\node_modules\nice-grpc\src\client\wrapClientError.ts:7
    return new ClientError(path, error.code, error.details);
           ^
ClientError: /HelloService/SayHello INTERNAL: Request message serialization failure: Cannot read properties of undefined (reading 'create')
    at wrapClientError (...\node_modules\.pnpm\nice-grpc@2.0.0\node_modules\nice-grpc\src\client\wrapClientError.ts:7:12)
    at Object.callback (...\node_modules\.pnpm\nice-grpc@2.0.0\node_modules\nice-grpc\src\client\createUnaryMethod.ts:63:35)
    at Object.onReceiveStatus (...\node_modules\.pnpm\@grpc+grpc-js@1.7.1\node_modules\@grpc\grpc-js\src\client.ts:358:26)
    at Object.onReceiveStatus (...\node_modules\.pnpm\@grpc+grpc-js@1.7.1\node_modules\@grpc\grpc-js\src\client-interceptors.ts:462:34)
    at Object.onReceiveStatus (...\node_modules\.pnpm\@grpc+grpc-js@1.7.1\node_modules\@grpc\grpc-js\src\client-interceptors.ts:424:48)
    at ...\node_modules\.pnpm\@grpc+grpc-js@1.7.1\node_modules\@grpc\grpc-js\src\call-stream.ts:330:24
    at processTicksAndRejections (node:internal/process/task_queues:77:11) {
  path: '/HelloService/SayHello',
  code: 13,
  details: "Request message serialization failure: Cannot read properties of undefined (reading 'create')"
}
```

Shouldn't that work?

I'm using Node v18.8.0 on Windows with pnpm if that matters.

**Comment by aikoven** [comment]
Can you please share the command that you compile protobufs with?

**Comment by some-user123** [comment]
Sure:

```jsonc
// package.json
{
  "scripts": {
    "generate": "grpc_tools_node_protoc --proto_path=./proto --ts_proto_out=./compiled_proto --ts_proto_opt=outputServices=nice-grpc,outputServices=generic-definitions,useExactTypes=false ./proto/hello.proto"
  },
  // ...
}
```

**Comment by aikoven** [comment]
That's interesting. Are you using ESM?

Can you please try it with NPM or Yarn?

My hypothesis is that it is caused by the import of `protobuf` in generated code:

```ts
import _m0 from 'protobufjs/minimal.js';
```

which is later used in `encode` methods:

```ts
encode(
  message: ModelVersionConfig,
  writer: _m0.Writer = _m0.Writer.create(),
): _m0.Writer {
```

Which version of `protobufjs` package are you using?

**Comment by some-user123** [comment]
Yes, I'm using ESM.

`--ts_proto_opt=...,esModuleInterop=true` fixed it.
