### ISSUE TITLE
Fetch Transport failing 

### ISSUE THREAD

**Issue by Blonteractor** [deeplay-io/nice-grpc#344]
```ts
import { createChannel, createClient } from "nice-grpc-web";
import { SchedulerDefinition } from "./proto/scheduler/scheduler";

const client = createClient(
	SchedulerDefinition,
	createChannel("http://localhost:10000")
);

client.echo({ text: "GEEGEE" }).then((response) => {
	console.log(response);
});
```
```
ClientError: /scheduler.Scheduler/Echo UNKNOWN: Transport error: fetch failed
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11457:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.fetchTransport [as transport] (/home/priyanshu/Dev/scheduler-web/client/node_modules/nice-grpc-web/lib/client/transports/fetch.js:43:26)
    at async handleTransportErrors (/home/priyanshu/Dev/scheduler-web/client/node_modules/nice-grpc-web/lib/client/makeCall.js:47:20)
    at async decodeResponse (/home/priyanshu/Dev/scheduler-web/client/node_modules/nice-grpc-web/lib/client/decodeResponse.js:14:22)
    at async makeCall (/home/priyanshu/Dev/scheduler-web/client/node_modules/nice-grpc-web/lib/client/makeCall.js:80:9)
    at async unaryMethod (/home/priyanshu/Dev/scheduler-web/client/node_modules/nice-grpc-web/lib/client/createUnaryMethod.js:22:26)
    at async Object.echo (/home/priyanshu/Dev/scheduler-web/client/node_modules/nice-grpc-web/lib/client/createUnaryMethod.js:48:22)
    at handleTransportErrors (/home/priyanshu/Dev/scheduler-web/client/node_modules/nice-grpc-web/lib/client/makeCall.js:60:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async decodeResponse (/home/priyanshu/Dev/scheduler-web/client/node_modules/nice-grpc-web/lib/client/decodeResponse.js:14:22)
    at async makeCall (/home/priyanshu/Dev/scheduler-web/client/node_modules/nice-grpc-web/lib/client/makeCall.js:80:9)
    at async unaryMethod (/home/priyanshu/Dev/scheduler-web/client/node_modules/nice-grpc-web/lib/client/createUnaryMethod.js:22:26)
    at async Object.echo (/home/priyanshu/Dev/scheduler-web/client/node_modules/nice-grpc-web/lib/client/createUnaryMethod.js:48:22) {
  path: '/scheduler.Scheduler/Echo',
  code: 2,
  details: 'Transport error: fetch failed\n' +
    'TypeError: fetch failed\n' +
    '    at Object.fetch (node:internal/deps/undici/undici:11457:11)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async Object.fetchTransport [as transport] (/home/priyanshu/Dev/scheduler-web/client/node_modules/nice-grpc-web/lib/client/transports/fetch.js:43:26)\n' +
    '    at async handleTransportErrors (/home/priyanshu/Dev/scheduler-web/client/node_modules/nice-grpc-web/lib/client/makeCall.js:47:20)\n' +
    '    at async decodeResponse (/home/priyanshu/Dev/scheduler-web/client/node_modules/nice-grpc-web/lib/client/decodeResponse.js:14:22)\n' +
    '    at async makeCall (/home/priyanshu/Dev/scheduler-web/client/node_modules/nice-grpc-web/lib/client/makeCall.js:80:9)\n' +
    '    at async unaryMethod (/home/priyanshu/Dev/scheduler-web/client/node_modules/nice-grpc-web/lib/client/createUnaryMethod.js:22:26)\n' +
    '    at async Object.echo (/home/priyanshu/Dev/scheduler-web/client/node_modules/nice-grpc-web/lib/client/createUnaryMethod.js:48:22)'
}
```

The server code is written using [tonic](https://github.com/hyperium/tonic), everythings fine with the server, it worked using `@grpc/grpc-js`. I am pretty lost on this, any help would be appreciated

**Comment by aikoven** [comment]
Please check the browser console and the Network tab. Unfortunately browsers report very little info to the exceptions thrown by `fetch`.

**Comment by Blonteractor** [comment]
Sorry if I sound retarded but how do I check that? No browser is involved here.

**Comment by aikoven** [comment]
Ah, sorry, I see that you're using NodeJS.

Are you running the grpc-web proxy in front of your server?

**Comment by Blonteractor** [comment]
I did not do that myself, but do not know if the library I used (tonic) does that automatically, but if this worked with `grpc-js` so probably (unless its nice-grpc only thing)

**Comment by aikoven** [comment]
`grpc-js` can talk the gRPC protocol directly, unlike `nice-grpc-web` that mainly targets browsers. Browsers can't directly communicate with gRPC servers and require a proxy, see https://github.com/deeplay-io/nice-grpc/blob/master/packages/nice-grpc-web/README.md#preparing-the-server

If you're targeting NodeJS, use the [nice-grpc](https://github.com/deeplay-io/nice-grpc/tree/master/packages/nice-grpc) package.

**Comment by Blonteractor** [comment]
```
import { createChannel, createClient } from "nice-grpc";
```
Worked! Thanks man o7
